#!/usr/bin/env node
const { execFileSync } = require("child_process");
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "../..");
const dist = path.join(root, "dist");
const manifestPath = path.join(dist, "manifest.json");
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
const version = manifest.version;
const releaseRoot = path.resolve(root, "..", "小梁RH发布包");
const releaseDir = path.join(releaseRoot, "XiaoLiangRH-" + version);
const packageZip = path.join(releaseDir, "XiaoLiangRH-" + version + ".zip");
const ccxPackage = path.join(releaseDir, "XiaoLiangRH-" + version + ".ccx");
const innoScript = path.join(releaseDir, "XiaoLiangRH-" + version + "-Installer.iss");
const innoOutputName = "XiaoLiangRH-" + version + "-Installer";
const installer = path.join(releaseDir, innoOutputName + ".exe");

function run(file, args, options) {
    execFileSync(file, args, { cwd: options && options.cwd ? options.cwd : root, stdio: "inherit" });
}

function hash(file) {
    return crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex");
}

function writeHash(file) {
    fs.writeFileSync(file + ".sha256", hash(file) + "  " + path.basename(file) + "\n", "utf8");
}

function psQuote(value) {
    return "'" + String(value).replace(/'/g, "''") + "'";
}

function createZipFromDist(output) {
    const tempZip = output.endsWith(".zip") ? output : output + ".zip";
    fs.rmSync(output, { force: true });
    fs.rmSync(tempZip, { force: true });
    run("powershell.exe", [
        "-NoProfile",
        "-Command",
        "Compress-Archive -Path " + psQuote(path.join(dist, "*")) + " -DestinationPath " + psQuote(tempZip) + " -Force",
    ]);
    if (tempZip !== output) fs.renameSync(tempZip, output);
}

function listZipEntries(archive) {
    const output = execFileSync("tar", ["-tf", archive], { encoding: "utf8" });
    return output.split(/\r?\n/).filter(Boolean);
}

function assertPackageShape(archive) {
    const entries = listZipEntries(archive);
    if (!entries.includes("manifest.json")) {
        throw new Error(path.basename(archive) + " root is missing manifest.json");
    }
}

function findInnoCompiler() {
    const candidates = [
        process.env.ISCC,
        path.join(process.env.LOCALAPPDATA || "", "Programs", "Inno Setup 6", "ISCC.exe"),
        "C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe",
        "C:\\Program Files\\Inno Setup 6\\ISCC.exe",
        "C:\\Program Files (x86)\\Inno Setup 5\\ISCC.exe",
        "C:\\Program Files\\Inno Setup 5\\ISCC.exe",
    ].filter(Boolean);
    for (const candidate of candidates) {
        if (fs.existsSync(candidate)) return candidate;
    }
    try {
        const found = execFileSync("where", ["ISCC.exe"], { encoding: "utf8" })
            .split(/\r?\n/)
            .map((line) => line.trim())
            .find(Boolean);
        return found || null;
    } catch {
        return null;
    }
}

function writeInnoScript() {
    const setupIcon = path.join(dist, "icons", "icon.ico");
    const lines = [
        "; Generated by scripts/release-installer/build-release.cjs",
        "#define MyAppName \"小梁RH\"",
        "#define MyAppVersion \"" + version + "\"",
        "#define MySourceDir \"" + dist + "\"",
        "#define MyOutputDir \"" + releaseDir + "\"",
        "",
        "[Setup]",
        "AppId={{B86F92BB-5215-4E06-9FBB-9E2A18A82316}",
        "AppName={#MyAppName}",
        "AppVersion={#MyAppVersion}",
        "AppPublisher=小梁",
        "DefaultDirName={code:GetDefaultPluginDir}",
        "ArchitecturesAllowed=x64compatible",
        "ArchitecturesInstallIn64BitMode=x64compatible",
        "DisableProgramGroupPage=yes",
        "OutputDir={#MyOutputDir}",
        "OutputBaseFilename=" + innoOutputName,
        "Compression=lzma2",
        "SolidCompression=yes",
        "WizardStyle=modern",
        "PrivilegesRequired=admin",
        "Uninstallable=no",
        "UsePreviousAppDir=no",
        "DirExistsWarning=no",
    ];
    if (fs.existsSync(setupIcon)) lines.push("SetupIconFile=" + setupIcon);
    lines.push(
        "",
        "[Languages]",
        "Name: \"chinesesimp\"; MessagesFile: \"compiler:Default.isl\"",
        "",
        "[Files]",
        "Source: \"{#MySourceDir}\\\\*\"; DestDir: \"{app}\"; Flags: ignoreversion recursesubdirs createallsubdirs",
        "",
        "[Code]",
        "function CleanPath(Value: String): String;",
        "begin",
        "  Result := Trim(Value);",
        "  StringChangeEx(Result, '/', '\\', True);",
        "end;",
        "",
        "function PluginDirFromPluginRoot(Value: String): String;",
        "begin",
        "  Value := CleanPath(Value);",
        "  Result := '';",
        "  if (Value <> '') and DirExists(Value) then",
        "    Result := AddBackslash(Value) + 'XiaoLiangRH';",
        "end;",
        "",
        "function PluginDirFromAppRoot(Value: String): String;",
        "var",
        "  Candidate: String;",
        "begin",
        "  Value := CleanPath(Value);",
        "  Result := '';",
        "  if Value = '' then",
        "    Exit;",
        "  Candidate := AddBackslash(Value) + 'Plug-ins';",
        "  if not DirExists(Candidate) then",
        "    Candidate := AddBackslash(Value) + 'Plug-Ins';",
        "  if DirExists(Candidate) then",
        "    Result := AddBackslash(Candidate) + 'XiaoLiangRH';",
        "end;",
        "",
        "function QueryRegistryValue(RootKey: Integer; KeyPath: String; ValueName: String; var Value: String): Boolean;",
        "begin",
        "  Result := RegQueryStringValue(RootKey, KeyPath, ValueName, Value);",
        "  if Result then",
        "    Value := CleanPath(Value);",
        "end;",
        "",
        "function QueryPluginPath(RootKey: Integer; KeyName: String; var Value: String): Boolean;",
        "var",
        "  KeyPath: String;",
        "begin",
        "  KeyPath := 'SOFTWARE\\Adobe\\Photoshop\\' + KeyName;",
        "  Result := QueryRegistryValue(RootKey, KeyPath, 'PluginPath', Value);",
        "  if not Result then",
        "    Result := QueryRegistryValue(RootKey, KeyPath + '\\PluginPath', '', Value);",
        "end;",
        "",
        "function QueryAppPath(RootKey: Integer; KeyName: String; var Value: String): Boolean;",
        "var",
        "  KeyPath: String;",
        "begin",
        "  KeyPath := 'SOFTWARE\\Adobe\\Photoshop\\' + KeyName;",
        "  Result := QueryRegistryValue(RootKey, KeyPath, 'ApplicationPath', Value);",
        "  if not Result then",
        "    Result := QueryRegistryValue(RootKey, KeyPath, 'InstallPath', Value);",
        "  if not Result then",
        "    Result := QueryRegistryValue(RootKey, KeyPath, 'Path', Value);",
        "end;",
        "",
        "function GetPhotoshopPluginDirFromRoot(RootKey: Integer): String;",
        "var",
        "  Names: TArrayOfString;",
        "  I: Integer;",
        "  Value: String;",
        "begin",
        "  Result := '';",
        "  if RegGetSubkeyNames(RootKey, 'SOFTWARE\\Adobe\\Photoshop', Names) then",
        "  begin",
        "    for I := GetArrayLength(Names) - 1 downto 0 do",
        "    begin",
        "      if QueryPluginPath(RootKey, Names[I], Value) then",
        "      begin",
        "        Result := PluginDirFromPluginRoot(Value);",
        "        if Result <> '' then Exit;",
        "      end;",
        "      if QueryAppPath(RootKey, Names[I], Value) then",
        "      begin",
        "        Result := PluginDirFromAppRoot(Value);",
        "        if Result <> '' then Exit;",
        "      end;",
        "    end;",
        "  end;",
        "end;",
        "",
        "function GetPhotoshopPluginDirFromRegistry(): String;",
        "begin",
        "  Result := '';",
        "  if IsWin64 then",
        "  begin",
        "    Result := GetPhotoshopPluginDirFromRoot(HKLM64);",
        "    if Result <> '' then Exit;",
        "  end;",
        "  Result := GetPhotoshopPluginDirFromRoot(HKLM32);",
        "  if Result <> '' then Exit;",
        "  Result := GetPhotoshopPluginDirFromRoot(HKCU);",
        "end;",
        "",
        "function GetFallbackPluginDir(): String;",
        "var",
        "  Candidate: String;",
        "begin",
        "  Candidate := ExpandConstant('{pf}\\Adobe\\Adobe Photoshop 2026\\Plug-ins');",
        "  if DirExists(Candidate) then",
        "  begin",
        "    Result := AddBackslash(Candidate) + 'XiaoLiangRH';",
        "    Exit;",
        "  end;",
        "  Candidate := ExpandConstant('{pf32}\\Adobe\\Adobe Photoshop 2026\\Plug-ins');",
        "  if DirExists(Candidate) then",
        "    Result := AddBackslash(Candidate) + 'XiaoLiangRH'",
        "  else",
        "    Result := ExpandConstant('{pf}\\Adobe\\Adobe Photoshop 2026\\Plug-ins\\XiaoLiangRH');",
        "end;",
        "",
        "function GetDefaultPluginDir(Param: String): String;",
        "var",
        "  RegistryDir: String;",
        "begin",
        "  RegistryDir := GetPhotoshopPluginDirFromRegistry();",
        "  if RegistryDir <> '' then",
        "    Result := RegistryDir",
        "  else",
        "    Result := GetFallbackPluginDir();",
        "end;",
    );
    fs.writeFileSync(innoScript, lines.join("\n") + "\n", "utf8");
}

function buildInstallerIfPossible() {
    writeInnoScript();
    fs.rmSync(installer, { force: true });
    fs.rmSync(installer + ".sha256", { force: true });
    const iscc = findInnoCompiler();
    if (!iscc) {
        console.log("installer: skipped, Inno Setup ISCC.exe not found");
        console.log("installer script: " + innoScript);
        return false;
    }
    run(iscc, [innoScript], { cwd: releaseDir });
    if (!fs.existsSync(installer)) throw new Error("Inno Setup did not create installer");
    writeHash(installer);
    return true;
}

function main() {
    if (!fs.existsSync(manifestPath)) throw new Error("dist is missing manifest.json");
    if (fs.readdirSync(dist).some((name) => name.endsWith(".map"))) {
        throw new Error("release dist must not contain source maps");
    }
    fs.mkdirSync(releaseDir, { recursive: true });
    for (const file of [packageZip, ccxPackage, packageZip + ".sha256", ccxPackage + ".sha256"]) {
        fs.rmSync(file, { force: true });
    }
    createZipFromDist(packageZip);
    createZipFromDist(ccxPackage);
    assertPackageShape(packageZip);
    assertPackageShape(ccxPackage);
    writeHash(packageZip);
    writeHash(ccxPackage);
    const hasInstaller = buildInstallerIfPossible();
    console.log("release: " + releaseDir);
    console.log("zip: " + packageZip);
    console.log("ccx: " + ccxPackage);
    console.log("installer: " + (hasInstaller ? installer : "not built"));
}

main();
